### ISSUE TITLE
projeto legal

### ISSUE THREAD

**Issue by ghost** [0kira-vgl/jogo-numero-secreto#1]

**Comment by 0kira-vgl** [comment]
O rapaz, muito obrigado.

**Comment by 0kira-vgl** [comment]
> não sei onde comentar, mas achei seu projeto legal

O rapaz, muito obrigado.

**Comment by lucasnuic** [comment]
posso te seguir aqui no github para acompanhar seus códigos?

**Comment by 0kira-vgl** [comment]
> posso te seguir aqui no github para acompanhar seus códigos?

Claro que pode meu amigo!

**Comment by lucasnuic** [comment]
poderia me ajudar em algo? queria saber sua opinião
